/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pasta;


public class App {


    public static void main(String[] args) {
    	Equipe equipeFerrari = new Equipe();
    	Equipe equipeFusca = new Equipe();
    	equipeFerrari.v1 = new Veiculo (new MotorDeFerrari());
    	equipeFusca.v2 = new Veiculo (new MotorDeFusca());
    	
    	equipeFerrari.p1 = new Piloto ("Schuaquer", 30);
    	equipeFusca.p2 = new Piloto ("Rubinho", 30);
    	
    	equipeFerrari.mecanicos.add(new Mecanico());
    	equipeFerrari.mecanicos.add(new Mecanico());
    	equipeFerrari.mecanicos.add(new Mecanico());
    	equipeFerrari.mecanicos.add(new Mecanico());
    	equipeFerrari.mecanicos.add(new Mecanico());
    	
    	
    equipeFusca.mecanicos.add(new Mecanico());
     equipeFusca.mecanicos.add(new Mecanico());
     equipeFusca.mecanicos.add(new Mecanico());
     equipeFusca.mecanicos.add(new Mecanico());
     equipeFusca.mecanicos.add(new Mecanico());
    	
    	
    	
    	
    	
    	System.out.println(equipeFerrari.v1.acelerar(5));
    	
    	System.out.println(equipeFusca.v2.acelerar(3));

    	
    	new Pessoa ();
    	new Piloto ("Nelson Piquet", 40);
    	MotorDeFerrari mFer = new MotorDeFerrari ();
    	new Veiculo (mFer);
    }
    
}

